[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.zap"

[deploy]
healthcheckPath = "/JSON/core/view/version/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
